/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AXIOO
 */
public class Order extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    DefaultTableModel model1 = new DefaultTableModel();
    DefaultTableModel model2 = new DefaultTableModel();
    Connection cn = koneksi.Koneksi.koneksiDb();
    
    public Order() {
        initComponents();
        
        judul1();
        judul2();
        tampilData("");
        tampilData2("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idpesanan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        iduser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idmenu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalHargaLabel = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmenu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelpesanan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 231, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idpesanan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(idpesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID User");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        iduser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(iduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-order-30.png"))); // NOI18N
        jLabel6.setText("Order");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Transaksi");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        idmenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(idmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("ID Menu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        totalHargaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalHargaLabel.setText("-");
        totalHargaLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalHargaLabelFocusLost(evt);
            }
        });
        totalHargaLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalHargaLabelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalHargaLabelKeyTyped(evt);
            }
        });
        jPanel1.add(totalHargaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jumlah.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahKeyReleased(evt);
            }
        });
        jPanel1.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Total Harga");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Tanggal Pemesanan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID Pesanan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        simpan.setBackground(new java.awt.Color(51, 153, 255));
        simpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setText("Simpan");
        simpan.setBorderPainted(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 90, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Jumlah");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Logout");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, 20));

        tabelmenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelmenu);

        jTabbedPane1.addTab("Menu", jScrollPane1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelpesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelpesanan);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 260));

        jTabbedPane1.addTab("Pesanan", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 540, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 530));

        setSize(new java.awt.Dimension(775, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        transaksi baru = new transaksi();
        baru.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
    try {
    Connection cn = koneksi.Koneksi.koneksiDb();
    Statement st = cn.createStatement();

    // Mengambil harga dari database berdasarkan ID menu yang diinputkan pengguna
    ResultSet rs = st.executeQuery("SELECT harga FROM menu WHERE id_menu = '" + idmenu.getText() + "'");
    int hargaMakanan = 0;
    if (rs.next()) {
        hargaMakanan = rs.getInt("harga");
    }

    // Menghitung total harga berdasarkan jumlah yang dimasukkan oleh pengguna
    int jumlahMakanan = Integer.parseInt(jumlah.getText());
    int totalHarga = jumlahMakanan * hargaMakanan;

    // Menyimpan data pesanan ke tabel pesanan
    st.executeUpdate("INSERT INTO pesanan (id_user, id_menu, jumlah, total_harga, tanggal_pemesanan, status) VALUES ('"
            + iduser.getText() + "','"
            + idmenu.getText() + "','"
            + jumlah.getText() + "','"
            + totalHarga + "', NOW(), 'belum dibayar')");

    // Mengambil status dari tabel pesanan
    ResultSet pesananRs = st.executeQuery("SELECT status FROM pesanan WHERE id_user = '" + iduser.getText() + "' ORDER BY id_pesanan DESC LIMIT 1");
    String statusPesanan = "belum dibayar";
    if (pesananRs.next()) {
        statusPesanan = pesananRs.getString("status");
    }

    // Menyimpan data transaksi dengan memasukkan nilai status dari tabel pesanan
    st.executeUpdate("INSERT INTO transaksi (id_user, total_bayar, tanggal_transaksi, status) VALUES ('2', '"
            + totalHarga + "', NOW(), '" + statusPesanan + "')");

    // Menampilkan total harga di JLabel "totalHarga"
    totalHargaLabel.setText(String.valueOf(totalHarga));

    // Menampilkan data pesanan
    tampilData("");

    JOptionPane.showMessageDialog(null, "Simpan Berhasil");
    idpesanan.setText("");
    iduser.setText("");
    idmenu.setText("");
    jumlah.setText("");
    totalHargaLabel.setText(""); // Mengosongkan totalHargaLabel
} catch (Exception e) {
    e.printStackTrace();
}


    }//GEN-LAST:event_simpanActionPerformed

    private void totalHargaLabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalHargaLabelKeyReleased
        
    }//GEN-LAST:event_totalHargaLabelKeyReleased

    private void totalHargaLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalHargaLabelFocusLost
        
    }//GEN-LAST:event_totalHargaLabelFocusLost

    private void totalHargaLabelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalHargaLabelKeyTyped
        
    }//GEN-LAST:event_totalHargaLabelKeyTyped

    private void jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyReleased
        try {
        // Mengambil harga dari database berdasarkan ID menu yang diinputkan pengguna
        Connection cn = koneksi.Koneksi.koneksiDb();
        Statement st = cn.createStatement();
        ResultSet rs = st.executeQuery("SELECT harga FROM menu WHERE id_menu = '" + idmenu.getText() + "'");

        int hargaMakanan = 0;
        if (rs.next()) {
            hargaMakanan = rs.getInt("harga");
        }

        // Menghitung total harga berdasarkan jumlah yang dimasukkan oleh pengguna
        int jumlahMakanan = Integer.parseInt(jumlah.getText());
        int totalHarga = jumlahMakanan * hargaMakanan;

        // Menampilkan total harga di JLabel "totalHarga"
        totalHargaLabel.setText(String.valueOf(totalHarga));

    } catch (Exception e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_jumlahKeyReleased

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        login.Login baru = new login.Login();
        baru.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idmenu;
    private javax.swing.JTextField idpesanan;
    private javax.swing.JTextField iduser;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelmenu;
    private javax.swing.JTable tabelpesanan;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JLabel totalHargaLabel;
    // End of variables declaration//GEN-END:variables
public void judul1() {
        Object[] judul = {
            "ID Menu", "Nama Menu", "Harga"
        };
        model1 = new DefaultTableModel(null, judul);
        tabelmenu.setModel(model1);
    }

public void tampilData(String where) {
        try {
            st = cn.createStatement();
            model1.getDataVector().removeAllElements();
            model1.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM menu " + where);
            
            while (rs.next()) {
                Object[] data = {
                    rs.getString("id_menu"),
                    rs.getString("nama_menu"),
                    rs.getString("harga"),
                };
                
                    model1.addRow(data);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
public void judul2() {
        Object[] judul = {
            "ID Pesanan", "ID User", "ID Menu", "Jumlah", "Total Harga", "Tanggal Pesan", "status"
        };
        model2 = new DefaultTableModel(null, judul);
        tabelpesanan.setModel(model2);
    }
public void tampilData2(String where) {
        try {
            st = cn.createStatement();
            model2.getDataVector().removeAllElements();
            model2.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM pesanan " + where);
            
            while (rs.next()) {
                Object[] data = {
                    rs.getString("id_pesanan"),
                    rs.getString("id_user"),
                    rs.getString("id_menu"),
                    rs.getString("jumlah"),
                    rs.getString("total_harga"),
                    rs.getString("tanggal_pemesanan"),
                    rs.getString("status"),
                };
                
                    model2.addRow(data);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
}
